FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN adduser --disabled-password appuser
WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .

RUN python manage.py collectstatic --noinput || true


RUN chown -R appuser:appuser /code
USER appuser

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
