# Generated by Django 5.2.4 on 2025-11-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='position',
            name='no_short_positions',
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_non_negative'),
        ),
    ]
