# Generated by Django 5.2.4 on 2025-11-25 00:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0007_dailypricehistory'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order')], default='MARKET', max_length=10)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Total quantity requested', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Quantity filled so far (for partial fills)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, help_text="Target price for LIMIT orders (in asset's currency)", max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Current holdings quantity', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('average_cost', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text="Weighted average purchase price per unit (in asset's currency)", max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative profit/loss from closed (sold) portions', max_digits=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='market.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('average_cost', models.DecimalField(decimal_places=8, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_price', models.DecimalField(blank=True, decimal_places=8, help_text='Market price at time of snapshot', max_digits=20, null=True)),
                ('unrealized_pnl', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated unrealized P&L at snapshot time', max_digits=20, null=True)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='trading.position')),
            ],
            options={
                'verbose_name': 'Position Snapshot',
                'verbose_name_plural': 'Position Snapshots',
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantity traded in this execution', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('price', models.DecimalField(decimal_places=8, help_text="Execution price per unit (in asset's currency)", max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Trading fee charged', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='market.asset')),
                ('fee_currency', models.ForeignKey(help_text='Currency in which fee is denominated', on_delete=django.db.models.deletion.PROTECT, related_name='trade_fees', to='market.currency')),
                ('order', models.ForeignKey(help_text='The order this trade fulfills', on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.OneToOneField(blank=True, help_text='The wallet Transaction recording currency movement for this trade', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade', to='wallets.transaction')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='trading_ord_user_id_ca9b05_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['asset', 'status', 'order_type'], name='trading_ord_asset_i_c3f5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='trading_ord_status_86d666_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', 'asset'], name='trading_pos_user_id_1a608d_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('user', 'asset'), name='unique_user_asset_position'),
        ),
        migrations.AddIndex(
            model_name='positionsnapshot',
            index=models.Index(fields=['position', '-snapshot_at'], name='trading_pos_positio_b42604_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', '-executed_at'], name='trading_tra_user_id_7b62ae_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['asset', '-executed_at'], name='trading_tra_asset_i_6300a2_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['order', 'executed_at'], name='trading_tra_order_i_c08bba_idx'),
        ),
    ]
