# Generated by Django 5.2.11 on 2026-04-19 15:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order')], default='MARKET', max_length=10)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantity to buy or sell', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, help_text="Target price for LIMIT orders (in asset's currency)", max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('reserved_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='For BUY: funds reserved in wallet. For SELL: not used (use reserved_quantity on Position)', max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of the snapshot')),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total portfolio value (positions) in base currency', max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total cost basis of all positions in base currency', max_digits=20)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total cash across all wallets in base currency', max_digits=20)),
                ('total_portfolio_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total_value + cash_balance in base currency', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Current holdings quantity', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pending_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Quantity reserved for pending SELL orders', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('average_cost', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text="Weighted average purchase price per unit (in asset's currency)", max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative profit/loss from closed (sold) portions', max_digits=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='market.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantity traded in this execution', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('price', models.DecimalField(decimal_places=8, help_text="Execution price per unit (in asset's currency)", max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Trading fee charged', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='market.asset')),
                ('fee_currency', models.ForeignKey(help_text='Currency in which fee is denominated', on_delete=django.db.models.deletion.PROTECT, related_name='trade_fees', to='market.currency')),
                ('order', models.ForeignKey(help_text='The order this trade fulfills', on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.OneToOneField(blank=True, help_text='The wallet Transaction recording currency movement for this trade', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade', to='wallets.transaction')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='trading_ord_user_id_ca9b05_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['asset', 'status', 'order_type'], name='trading_ord_asset_i_c3f5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='trading_ord_status_86d666_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['user', '-date'], name='trading_por_user_id_d24798_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_portfolio_snapshot_per_day'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', 'asset'], name='trading_pos_user_id_1a608d_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('user', 'asset'), name='unique_user_asset_position'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', '-executed_at'], name='trading_tra_user_id_7b62ae_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['asset', '-executed_at'], name='trading_tra_asset_i_6300a2_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['order', 'executed_at'], name='trading_tra_order_i_c08bba_idx'),
        ),
    ]
