# Generated by Django 5.2.4 on 2026-01-26 19:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='filled_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='For BUY: funds reserved in wallet. For SELL: not used (use reserved_quantity on Position)', max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='pending_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Quantity reserved for pending SELL orders', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=8, help_text='Quantity to buy or sell', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
