# Generated by Django 5.2.4 on 2026-02-09 15:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_order_filled_quantity_order_reserved_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of the snapshot')),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total portfolio value (positions) in base currency', max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total cost basis of all positions in base currency', max_digits=20)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total cash across all wallets in base currency', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='PositionSnapshot',
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['user', '-date'], name='trading_por_user_id_d24798_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_portfolio_snapshot_per_day'),
        ),
    ]
