# Generated by Django 5.2.11 on 2026-04-17 19:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='total_portfolio_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total_value + cash_balance in base currency', max_digits=20),
        ),
    ]
