# Generated by Django 5.2.4 on 2025-11-05 13:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', '-timestamp'], name='market_fxra_base_cu_b13d8e_idx')],
                'unique_together': {('base_currency', 'quote_currency', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=3)),
                ('tick_size', models.DecimalField(decimal_places=6, default=Decimal('0.01'), max_digits=12)),
                ('lot_size', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='PriceBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=6, max_digits=18)),
                ('high', models.DecimalField(decimal_places=6, max_digits=18)),
                ('low', models.DecimalField(decimal_places=6, max_digits=18)),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('volume', models.BigIntegerField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('bid', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('ask', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.instrument')),
            ],
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['currency', 'active'], name='market_inst_currenc_84cac8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('ticker', 'exchange')},
        ),
        migrations.AddIndex(
            model_name='pricebar',
            index=models.Index(fields=['instrument', '-period_start'], name='market_pric_instrum_1549e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricebar',
            unique_together={('instrument', 'period_start')},
        ),
    ]
