# Generated by Django 5.2.4 on 2025-11-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='close',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='high',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='low',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='open',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='volume',
        ),
    ]
