# Generated by Django 5.2.4 on 2025-11-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_exchange_close_time_exchange_open_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='source',
            field=models.CharField(choices=[('SIMULATION', 'Simulated Data'), ('LIVE', 'Live API Data')], default='Simulated Data', max_length=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['asset', 'timestamp', 'source'], name='market_pric_asset_i_082a2f_idx'),
        ),
    ]
