# Generated by Django 5.2.4 on 2025-11-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_currencyasset_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('CURRENCY', 'Currency')], max_length=10),
        ),
    ]
