# Generated by Django 5.2.4 on 2025-11-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_exchange_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.asset')),
            ],
            bases=('market.asset',),
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'currencies'},
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('CURRENCY', 'Currency')], default='STOCK', max_length=10),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='market.exchange'),
        ),
        migrations.DeleteModel(
            name='CurrencyPair',
        ),
    ]
