# Generated by Django 5.2.4 on 2025-11-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_pricehistory_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('volume', models.BigIntegerField()),
                ('source', models.CharField(choices=[('SIMULATION', 'Simulated Data'), ('LIVE', 'Live API Data')], max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_price_history', to='market.asset')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
                'indexes': [models.Index(fields=['asset', 'date', 'source'], name='market_dail_asset_i_ea1ab4_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
