# Generated by Django 5.2.4 on 2026-01-28 00:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_dailypricehistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='asset',
        ),
        migrations.CreateModel(
            name='PriceCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.PositiveIntegerField()),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(choices=[('SIMULATION', 'Simulated Data'), ('LIVE', 'Live API Data')], max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_candles', to='market.asset')),
            ],
            options={
                'ordering': ['-start_at'],
                'get_latest_by': 'start_at',
            },
        ),
        migrations.DeleteModel(
            name='DailyPriceHistory',
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.AddIndex(
            model_name='pricecandle',
            index=models.Index(fields=['asset', 'interval_minutes', 'start_at', 'source'], name='market_pric_asset_i_c89ea2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricecandle',
            unique_together={('asset', 'interval_minutes', 'start_at')},
        ),
    ]
