# Generated by Django 5.2.4 on 2026-01-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_pricehistory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='asset_ptr',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='exchange',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.AddField(
            model_name='asset',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.exchange'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('FUTURE', 'Future'), ('OPTION', 'Option')], max_length=10),
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=19)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency_rates', to='market.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency_rates', to='market.currency')),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
        migrations.DeleteModel(
            name='CurrencyAsset',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
