# Generated by Django 5.2.4 on 2026-01-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_stock_asset_ptr_remove_stock_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.exchange'),
        ),
    ]
