# Generated by Django 5.2.4 on 2026-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_asset_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('ticker', 'exchange')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['ticker', 'exchange'], name='market_asse_ticker_187f1d_idx'),
        ),
    ]
