# Generated by Django 5.2.4 on 2026-02-09 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0013_alter_exchange_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='base_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='market.currency'),
            preserve_default=False,
        ),
    ]
