# Generated by Django 5.2.4 on 2026-02-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_base_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='base_currency',
            new_name='home_currency',
        ),
    ]
