# Generated by Django 5.2.4 on 2025-07-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cash_balance',
            new_name='cash_balance_gbp',
        ),
    ]
