# Generated by Django 5.2.11 on 2026-04-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leaderboard_visible',
            field=models.BooleanField(default=True),
        ),
    ]
