# Generated by Django 5.2.11 on 2026-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_leaderboard_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
