# Generated by Django 5.2.4 on 2026-01-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_pending_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='pending_balance',
            new_name='available_balance',
        ),
    ]
