# Generated by Django 5.2.4 on 2026-01-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_rename_pending_balance_wallet_available_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='available_balance',
            new_name='pending_balance',
        ),
    ]
