# Generated by Django 5.2.4 on 2026-01-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_rename_available_balance_wallet_pending_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAWAL', 'WITHDRAWAL'), ('BUY', 'BUY'), ('SELL', 'SELL'), ('FX_TRANSFER', 'FX_TRANSFER')], max_length=16),
        ),
    ]
