# Generated by Django 5.2.4 on 2025-10-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Gbp'), ('USD', 'Usd'), ('EUR', 'Eur')], default='GBP', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Gbp'), ('USD', 'Usd'), ('EUR', 'Eur')], default='GBP', max_length=10),
        ),
    ]
