# Generated by Django 5.2.4 on 2025-10-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_remove_wallet_id_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='source',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BUY', 'Buy'), ('SELL', 'Sell')], default='DEPOSIT', max_length=10),
            preserve_default=False,
        ),
    ]
