# Generated by Django 5.2.4 on 2025-10-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_transaction_currency_alter_wallet_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
    ]
