# Generated by Django 5.2.4 on 2025-10-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_cashtransaction_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashTransaction',
            new_name='Transaction',
        ),
    ]
