# Generated by Django 5.2.4 on 2025-10-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_remove_transaction_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fx_Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_transfers_from', to='wallets.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_transfers_to', to='wallets.wallet')),
            ],
        ),
    ]
