# Generated by Django 5.2.4 on 2025-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_fx_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BUY', 'Buy'), ('SELL', 'Sell'), ('FX_TRANSFER', 'FX_TRANSFER')], max_length=16),
        ),
    ]
